GET http://localhost:3000/users

###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "id": 4,
    "email": "kalle@mail.se",
    "password": "12345"
}